### PR TITLE
Update ssa.py

### PR DESCRIPTION
**Pull request by fffarina**
Added the self.till_end attribute for the user to choose if he wants the simulation to stop when no valid reactions are found or if he wants to continue till the end of time or time steps he indicated. In case he chooses to don't stop the simulation but doesn't indicate desired end time or total time steps, raises an exception.

### CODE REVIEW

**Comment by wfatherley** [comment]
This will definitely be useful especially for random switches and other types of non-kinetic dynamics

**Comment by wfatherley** [comment]
Kind of silly, but I changed the name of the parameter to `until_end`

**Review by wfatherley — COMMENTED** [review]
I'm having second thoughts about `until_end` for the following reason. Suppose the user wishes to push the simulation to some prescribed number of steps or some elapsed time. In the case where no valid event can occur, all propensity `lambda`s will evaluate to `0`, throwing `ZeroDivisionError` in both `SSA.direct`, and `SSA.first_reaction` when generating that step's exponentially distributed sojourn time. The theoretical implication of of all propensities being zero would be some sort of equilibrium, so it feels like maybe the theoretically "justifiable" implementation of the genetic switch with SSA would be to have a set of events whose propensities are not dynamical, and whose corresponding stoichiometries can alter populations involved in events with dynamical propensities?

**Comment by fffarina** [comment]
If I remember correctly until_end was added because the simulation would run forever for models that do not reach equilibrium. StochPy also enforces to decide pre-simulation if you're going to use time steps or time to give an end point to the simulation. You can bypass that control only using the DoCompleteStochSim method. I think a feature like this is crucial, since the models can potentially lead to equilibrium/non equilibrium situations. Your concern seems however legit to me. I will take a look at it once I am done with my thesis and have a bit more time.

________________________________
Van: Will Fatherley ***@***.***>
Verzonden: maandag 28 juni 2021 05:48
Aan: wefatherley/monte-carlo
CC: Farina, F.F. (Fulvio); Author
Onderwerp: Re: [wefatherley/monte-carlo] Update ssa.py (#5)


@wefatherley commented on this pull request.

I'm having second thoughts about until_end for the following reason. Suppose the user wishes to push the simulation to some prescribed number of steps or some elapsed time. In the case where no valid event can occur, all propensity lambdas will evaluate to 0, throwing ZeroDivisionError in both SSA.direct, and SSA.first_reaction when generating that step's exponentially distributed sojourn time. The theoretical implication of of all propensities being zero would be some sort of equilibrium, so it feels like maybe the theoretically "justifiable" implementation of the genetic switch with SSA would be to have a set of events whose propensities are not dynamical, and whose corresponding stoichiometries can alter populations involved in events with dynamical propensities?

-

**Pull request merged**
